#!/usr/bin/env bash
#installs and configures haproxy on the load balancer

# Install HAproxy

if [ "$(which haproxy)" == "" ]
then
	sudo apt-get -y upgrade && \
	sudo apt-get -y install --no-install-recommends software-properties-common && \
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.8 && \
	sudo apt-get -y install haproxy=2.8.\*
fi

# Edit the config file
config="
frontend front
	bind *:80
	mode http
	default_backend webservers

backend webservers
	option h1-case-adjust-bogus-server
	balance roundrobin
	server 476489-web-01 52.204.77.251:80 check
	server 476489-web-02 100.26.17.117:80 check
"

echo "$config" >> /etc/haproxy/haproxy.cfg

# Ensure haproxy can be managed by an init script
echo "ENABLED=1" >> /etc/default/haproxy

# Restart haproxy
sudo service haproxy restart
