#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get install -y haproxy=2.9.\*

echo '
frontend front
        bind 0:80
                default_backend server_backend

backend server_backend
        balance roundrobin
        server 476489-web-01 52.204.77.251:80 check
        server 476489-web-02 100.26.17.117:80 check
 ' >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
