#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 476489-web-01:80 check
    server web-02 476489-web-02:80 check
EOF

service haproxy start
